# Generated by Django 5.0.7 on 2024-07-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('cuisine', models.CharField(max_length=200)),
            ],
        ),
    ]
